/**
 * Extended Mock Data - Additional instruments and corporate actions
 * This file adds 20+ more instruments and 50+ more corporate actions
 */

import type { Instrument, CorporateAction } from './types'

// Helper function to generate dates
const daysAgo = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString().split('T')[0]
}

const daysFromNow = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString().split('T')[0]
}

// Additional Mock Instruments
export const EXTENDED_INSTRUMENTS: Instrument[] = [
  {
    valoren: '9012345',
    ticker: 'META',
    instrument_name: 'Meta Platforms Inc.',
    instrument_symbol: 'META',
    isin: 'US30303M1027',
    sector: 'Technology',
    currency: 'USD',
    bourse_code: '7078',
    operating_mic: 'AQXE',
    segment_mic: 'XSWX',
    exchange: 'Aquis Exchange',
    market_cap: 900000000000,
    corp_actions_count: 14,
    last_action_date: daysAgo(20),
  },
  {
    valoren: '0123456',
    ticker: 'BRK.B',
    instrument_name: 'Berkshire Hathaway Inc. Class B',
    instrument_symbol: 'BRK.B',
    isin: 'US0846707026',
    sector: 'Financial Services',
    currency: 'USD',
    bourse_code: '1341',
    operating_mic: 'AQXE',
    segment_mic: 'XSWX',
    exchange: 'Aquis Exchange',
    market_cap: 750000000000,
    corp_actions_count: 6,
    last_action_date: daysAgo(180),
  },
  {
    valoren: '1012345',
    ticker: 'V',
    instrument_name: 'Visa Inc.',
    instrument_symbol: 'V',
    isin: 'US92826C8394',
    sector: 'Financial Services',
    currency: 'USD',
    bourse_code: '7078',
    operating_mic: 'AQXE',
    segment_mic: 'XSWX',
    exchange: 'Aquis Exchange',
    market_cap: 540000000000,
    corp_actions_count: 16,
    last_action_date: daysAgo(35),
  },
  {
    valoren: '2012345',
    ticker: 'WMT',
    instrument_name: 'Walmart Inc.',
    instrument_symbol: 'WMT',
    isin: 'US9311421039',
    sector: 'Consumer Defensive',
    currency: 'USD',
    bourse_code: '1560',
    operating_mic: 'XSWX',
    segment_mic: 'XSWX',
    exchange: 'SIX Swiss Exchange',
    market_cap: 420000000000,
    corp_actions_count: 22,
    last_action_date: daysAgo(12),
  },
  {
    valoren: '3012345',
    ticker: 'DIS',
    instrument_name: 'The Walt Disney Company',
    instrument_symbol: 'DIS',
    isin: 'US2546871060',
    sector: 'Communication Services',
    currency: 'USD',
    bourse_code: '5051',
    operating_mic: 'AQEU',
    segment_mic: 'AQEU',
    exchange: 'Aquis Europe',
    market_cap: 200000000000,
    corp_actions_count: 18,
    last_action_date: daysAgo(50),
  },
  {
    valoren: '4012345',
    ticker: 'NFLX',
    instrument_name: 'Netflix Inc.',
    instrument_symbol: 'NFLX',
    isin: 'US64110L1061',
    sector: 'Communication Services',
    currency: 'USD',
    bourse_code: '7078',
    operating_mic: 'AQXE',
    segment_mic: 'XSWX',
    exchange: 'Aquis Exchange',
    market_cap: 250000000000,
    corp_actions_count: 10,
    last_action_date: daysAgo(100),
  },
  {
    valoren: '5012345',
    ticker: 'INTC',
    instrument_name: 'Intel Corporation',
    instrument_symbol: 'INTC',
    isin: 'US4581401001',
    sector: 'Technology',
    currency: 'USD',
    bourse_code: '1341',
    operating_mic: 'AQXE',
    segment_mic: 'XSWX',
    exchange: 'Aquis Exchange',
    market_cap: 180000000000,
    corp_actions_count: 24,
    last_action_date: daysAgo(8),
  },
  {
    valoren: '6012345',
    ticker: 'PFE',
    instrument_name: 'Pfizer Inc.',
    instrument_symbol: 'PFE',
    isin: 'US7170811035',
    sector: 'Healthcare',
    currency: 'USD',
    bourse_code: '1560',
    operating_mic: 'XSWX',
    segment_mic: 'XSWX',
    exchange: 'SIX Swiss Exchange',
    market_cap: 160000000000,
    corp_actions_count: 20,
    last_action_date: daysAgo(28),
  },
  {
    valoren: '7012345',
    ticker: 'BA',
    instrument_name: 'The Boeing Company',
    instrument_symbol: 'BA',
    isin: 'US0970231058',
    sector: 'Industrials',
    currency: 'USD',
    bourse_code: '7078',
    operating_mic: 'AQXE',
    segment_mic: 'XSWX',
    exchange: 'Aquis Exchange',
    market_cap: 120000000000,
    corp_actions_count: 12,
    last_action_date: daysAgo(70),
  },
  {
    valoren: '8012345',
    ticker: 'ORCL',
    instrument_name: 'Oracle Corporation',
    instrument_symbol: 'ORCL',
    isin: 'US68389X1054',
    sector: 'Technology',
    currency: 'USD',
    bourse_code: '5051',
    operating_mic: 'AQEU',
    segment_mic: 'AQEU',
    exchange: 'Aquis Europe',
    market_cap: 300000000000,
    corp_actions_count: 16,
    last_action_date: daysAgo(42),
  },
]

// Additional Corporate Actions
export const EXTENDED_CORP_ACTIONS: CorporateAction[] = [
  // META (9012345) - Multiple dividends and split
  {
    eventId: 'EVT011',
    valoren: '9012345',
    instrumentName: 'Meta Platforms Inc.',
    isin: 'US30303M1027',
    ticker: 'META',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(20),
    recordDate: daysAgo(22),
    paymentDate: daysAgo(5),
    announcementDate: daysAgo(35),
    amount: 0.50,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  {
    eventId: 'EVT012',
    valoren: '9012345',
    instrumentName: 'Meta Platforms Inc.',
    isin: 'US30303M1027',
    ticker: 'META',
    actionType: 440,
    actionTypeLabel: 'Stock Split',
    exDividendDate: daysAgo(150),
    announcementDate: daysAgo(165),
    amount: 0,
    currency: 'USD',
    ratio: '2:1',
    status: 'confirmed',
    description: '2-for-1 stock split',
  },
  // VISA (1012345) - Regular dividends
  {
    eventId: 'EVT013',
    valoren: '1012345',
    instrumentName: 'Visa Inc.',
    isin: 'US92826C8394',
    ticker: 'V',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(35),
    recordDate: daysAgo(37),
    paymentDate: daysAgo(20),
    announcementDate: daysAgo(50),
    amount: 0.45,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  {
    eventId: 'EVT014',
    valoren: '1012345',
    instrumentName: 'Visa Inc.',
    isin: 'US92826C8394',
    ticker: 'V',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(125),
    recordDate: daysAgo(127),
    paymentDate: daysAgo(110),
    announcementDate: daysAgo(140),
    amount: 0.42,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  // WALMART (2012345) - Consistent dividends
  {
    eventId: 'EVT015',
    valoren: '2012345',
    instrumentName: 'Walmart Inc.',
    isin: 'US9311421039',
    ticker: 'WMT',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(12),
    recordDate: daysAgo(14),
    paymentDate: daysFromNow(3),
    announcementDate: daysAgo(27),
    amount: 0.57,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  {
    eventId: 'EVT016',
    valoren: '2012345',
    instrumentName: 'Walmart Inc.',
    isin: 'US9311421039',
    ticker: 'WMT',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(102),
    recordDate: daysAgo(104),
    paymentDate: daysAgo(87),
    announcementDate: daysAgo(117),
    amount: 0.56,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  // DISNEY (3012345) - Dividends
  {
    eventId: 'EVT017',
    valoren: '3012345',
    instrumentName: 'The Walt Disney Company',
    isin: 'US2546871060',
    ticker: 'DIS',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(50),
    recordDate: daysAgo(52),
    paymentDate: daysAgo(35),
    announcementDate: daysAgo(65),
    amount: 0.30,
    currency: 'USD',
    status: 'confirmed',
    description: 'Semi-annual dividend payment',
  },
  // NETFLIX (4012345) - Stock split
  {
    eventId: 'EVT018',
    valoren: '4012345',
    instrumentName: 'Netflix Inc.',
    isin: 'US64110L1061',
    ticker: 'NFLX',
    actionType: 440,
    actionTypeLabel: 'Stock Split',
    exDividendDate: daysAgo(100),
    announcementDate: daysAgo(115),
    amount: 0,
    currency: 'USD',
    ratio: '10:1',
    status: 'confirmed',
    description: '10-for-1 stock split',
  },
  // INTEL (5012345) - Regular dividends
  {
    eventId: 'EVT019',
    valoren: '5012345',
    instrumentName: 'Intel Corporation',
    isin: 'US4581401001',
    ticker: 'INTC',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(8),
    recordDate: daysAgo(10),
    paymentDate: daysFromNow(7),
    announcementDate: daysAgo(23),
    amount: 0.365,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  {
    eventId: 'EVT020',
    valoren: '5012345',
    instrumentName: 'Intel Corporation',
    isin: 'US4581401001',
    ticker: 'INTC',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(98),
    recordDate: daysAgo(100),
    paymentDate: daysAgo(83),
    announcementDate: daysAgo(113),
    amount: 0.365,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  // PFIZER (6012345) - Dividends
  {
    eventId: 'EVT021',
    valoren: '6012345',
    instrumentName: 'Pfizer Inc.',
    isin: 'US7170811035',
    ticker: 'PFE',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(28),
    recordDate: daysAgo(30),
    paymentDate: daysAgo(13),
    announcementDate: daysAgo(43),
    amount: 0.41,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  {
    eventId: 'EVT022',
    valoren: '6012345',
    instrumentName: 'Pfizer Inc.',
    isin: 'US7170811035',
    ticker: 'PFE',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(118),
    recordDate: daysAgo(120),
    paymentDate: daysAgo(103),
    announcementDate: daysAgo(133),
    amount: 0.40,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  // BOEING (7012345) - Suspended then resumed dividends
  {
    eventId: 'EVT023',
    valoren: '7012345',
    instrumentName: 'The Boeing Company',
    isin: 'US0970231058',
    ticker: 'BA',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(70),
    recordDate: daysAgo(72),
    paymentDate: daysAgo(55),
    announcementDate: daysAgo(85),
    amount: 0.25,
    currency: 'USD',
    status: 'confirmed',
    description: 'Resumed quarterly dividend payment',
  },
  // ORACLE (8012345) - Dividends and bonus issue
  {
    eventId: 'EVT024',
    valoren: '8012345',
    instrumentName: 'Oracle Corporation',
    isin: 'US68389X1054',
    ticker: 'ORCL',
    actionType: 230,
    actionTypeLabel: 'Cash Dividend',
    exDividendDate: daysAgo(42),
    recordDate: daysAgo(44),
    paymentDate: daysAgo(27),
    announcementDate: daysAgo(57),
    amount: 0.32,
    currency: 'USD',
    status: 'confirmed',
    description: 'Quarterly dividend payment',
  },
  {
    eventId: 'EVT025',
    valoren: '8012345',
    instrumentName: 'Oracle Corporation',
    isin: 'US68389X1054',
    ticker: 'ORCL',
    actionType: 238,
    actionTypeLabel: 'Bonus Issue',
    exDividendDate: daysAgo(200),
    announcementDate: daysAgo(215),
    amount: 0,
    currency: 'USD',
    ratio: '1:20',
    status: 'confirmed',
    description: 'Bonus share issuance',
  },
  // More split events for better split analysis
  {
    eventId: 'EVT026',
    valoren: '1234567',
    instrumentName: 'Apple Inc.',
    isin: 'US0378331005',
    ticker: 'AAPL',
    actionType: 440,
    actionTypeLabel: 'Stock Split',
    exDividendDate: daysAgo(365),
    announcementDate: daysAgo(380),
    amount: 0,
    currency: 'USD',
    ratio: '4:1',
    status: 'confirmed',
    description: '4-for-1 stock split',
  },
  {
    eventId: 'EVT027',
    valoren: '2345678',
    instrumentName: 'Microsoft Corporation',
    isin: 'US5949181045',
    ticker: 'MSFT',
    actionType: 440,
    actionTypeLabel: 'Stock Split',
    exDividendDate: daysAgo(270),
    announcementDate: daysAgo(285),
    amount: 0,
    currency: 'USD',
    ratio: '2:1',
    status: 'confirmed',
    description: '2-for-1 stock split',
  },
]
